version: '3.1'

services:
  database:
        restart: always
        #volumes:
        #   - './.data/wordpress:/var/www/html/'
        build:
          context: ./
          dockerfile: csv2mysql.dockerfile
            
        environment:
          MYSQL_ROOT_PASSWORD: superpass
          MYSQL_DATABASE: mydb
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - "3306:3306"
          #- "443:443"
          # - './path/on/docker/host:/path/inside/container'  
          # - .:/code
        #environment:
        #  DB_HOST_ENV: 127.0.0.1
        #  DB_NAME_ENV: db
        #  DB_USER_ENV: admin
        #  DB_PASS_ENV:
      # redis:
      #   image: "redis:alpine"
      # docker-compose up --force-recreate --renew-anon-volumes --build
      # docker-compose up -d
  metabase:
    # docker run -d -p 3000:3000 --name metabase metabase/metabase
    # container_name: database_mysql
    depends_on:
        - database
    links:
        - database  
    restart: always
    image: metabase/metabase:latest
    environment:
        MB_DB_TYPE : mysql
        MB_DB_DBNAME : mydb
        MB_DB_PORT : 3306
        MB_DB_USER : root
        MB_DB_PASS : superpass
        MB_DB_HOST : database
        #https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-metabase-on-docker.md
        #https://medium.com/@martinahindura/how-to-setup-metabase-with-postgresql-and-docker-compose-bf4cc7e7f899
        #https://github.com/Tinitto/compose-postgres-metabase
        #https://www.metabase.com/docs/v0.36.2/getting-started.html


        #MYSQL_ROOT_PASSWORD: superpass
        #MYSQL_DATABASE: mydb
        #MYSQL_USER: admin
        #MYSQL_PASSWORD: admin
    #volumes:
        # - my-datavolume:/var/lib/mysql  
        # - './.data/mysql:/var/lib/mysql'
    ports:
        - "3000:3000"
  # redis:
  #   image: "redis:alpine"
  # docker-compose up --force-recreate --renew-anon-volumes --build
  # docker-compose up -d